package com.google.mediapipe.examples.gesturerecognizer.dj

object DjGestureConfiguration {
    fun defaultBindings(): List<DjGestureBinding> = listOf(
        DjGestureBinding(
            id = "open-palm-play-pause",
            gestureName = "Open_Palm",
            command = DjCommand.PlayPauseDeckA,
            triggerMode = DjTriggerMode.OncePerHold,
            movement = MovementDirection.Still,
            minHoldMs = 150L,
        ),
        DjGestureBinding(
            id = "closed-fist-cue",
            gestureName = "Closed_Fist",
            command = DjCommand.CueDeckA,
            triggerMode = DjTriggerMode.OncePerHold,
            minHoldMs = 250L,
        ),
        DjGestureBinding(
            id = "thumb-up-volume-up",
            gestureName = "Thumb_Up",
            command = DjCommand.VolumeUpDeckA,
            triggerMode = DjTriggerMode.RepeatWhileHeld,
            repeatIntervalMs = 260L,
        ),
        DjGestureBinding(
            id = "thumb-down-volume-down",
            gestureName = "Thumb_Down",
            command = DjCommand.VolumeDownDeckA,
            triggerMode = DjTriggerMode.RepeatWhileHeld,
            repeatIntervalMs = 260L,
        ),
        DjGestureBinding(
            id = "pointing-up-filter-up",
            gestureName = "Pointing_Up",
            command = DjCommand.FilterUpDeckA,
            triggerMode = DjTriggerMode.RepeatWhileHeld,
            movement = MovementDirection.Up,
            repeatIntervalMs = 140L,
        ),
        DjGestureBinding(
            id = "pointing-up-filter-down",
            gestureName = "Pointing_Up",
            command = DjCommand.FilterDownDeckA,
            triggerMode = DjTriggerMode.RepeatWhileHeld,
            movement = MovementDirection.Down,
            repeatIntervalMs = 140L,
        ),
        DjGestureBinding(
            id = "open-palm-crossfader-left",
            gestureName = "Open_Palm",
            command = DjCommand.CrossfaderLeft,
            triggerMode = DjTriggerMode.ContinuousWhileHeld,
            movement = MovementDirection.Left,
            minHoldMs = 300L,
            repeatIntervalMs = 90L,
        ),
        DjGestureBinding(
            id = "open-palm-crossfader-right",
            gestureName = "Open_Palm",
            command = DjCommand.CrossfaderRight,
            triggerMode = DjTriggerMode.ContinuousWhileHeld,
            movement = MovementDirection.Right,
            minHoldMs = 300L,
            repeatIntervalMs = 90L,
        ),
        DjGestureBinding(
            id = "victory-crossfader-center",
            gestureName = "Victory",
            command = DjCommand.CrossfaderCenter,
            triggerMode = DjTriggerMode.OncePerHold,
            movement = MovementDirection.Still,
            minHoldMs = 150L,
        ),
        DjGestureBinding(
            id = "victory-fx-mix-up",
            gestureName = "Victory",
            command = DjCommand.FxMixUpDeckA,
            triggerMode = DjTriggerMode.RepeatWhileHeld,
            movement = MovementDirection.Up,
            repeatIntervalMs = 140L,
        ),
        DjGestureBinding(
            id = "victory-fx-mix-down",
            gestureName = "Victory",
            command = DjCommand.FxMixDownDeckA,
            triggerMode = DjTriggerMode.RepeatWhileHeld,
            movement = MovementDirection.Down,
            repeatIntervalMs = 140L,
        ),
        DjGestureBinding(
            id = "i-love-you-reset",
            gestureName = "ILoveYou",
            command = DjCommand.ResetDeckA,
            triggerMode = DjTriggerMode.OncePerHold,
            verticalZones = setOf(VerticalZone.Bottom),
            minHoldMs = 900L,
        ),
        DjGestureBinding(
            id = "i-love-you-fx-toggle",
            gestureName = "ILoveYou",
            command = DjCommand.ToggleFxDeckA,
            triggerMode = DjTriggerMode.OncePerHold,
        ),
    )
}
